# SPDX-FileCopyrightText: 2020 Evandro Chagas Ribeiro da Rosa <evandro@quantuloop.com>
# SPDX-FileCopyrightText: 2020 Rafael de Santiago <r.santiago@ufsc.br>
#
# SPDX-License-Identifier: Apache-2.0

stages:
  - lint
  - build
  - test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

Package Linux x86_64 Wheels:
  image: ghcr.io/astral-sh/uv:python3.10-trixie-slim
  stage: build
  variables:
    KBW_PROJ_ID: "16627872"
    LIBKET_PROJ_ID: "16638729"
    KBW_PATH: "src/ket/clib/libs/kbw"
    LIBKET_PATH: "src/ket/clib/libs/libket"
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git curl ca-certificates
    - rm -rf /var/lib/apt/lists/*
    - uv pip install --system build auditwheel patchelf
  script:
    - KBW_HASH=$(git rev-parse --short=8 HEAD:${KBW_PATH})
    - LIBKET_HASH=$(git rev-parse --short=8 HEAD:${LIBKET_PATH})
    - |
      curl --fail --location \
      "https://gitlab.com/api/v4/projects/${KBW_PROJ_ID}/packages/generic/kbw/${KBW_HASH}/libkbw.so" \
      --create-dirs --output src/ket/clib/libs/libkbw.so
    - |
      curl --fail --location \
      "https://gitlab.com/api/v4/projects/${LIBKET_PROJ_ID}/packages/generic/libket/${LIBKET_HASH}/libket.so" \
      --create-dirs --output src/ket/clib/libs/libket.so

    - python -m build -w
    - python -m auditwheel repair --plat manylinux_2_28_x86_64 dist/ket_lang*.whl
  artifacts:
    paths:
      - wheelhouse/*.whl

Package Windows x86_64 Wheels:
  image: ghcr.io/astral-sh/uv:python3.10-trixie-slim
  stage: build
  variables:
    KBW_PROJ_ID: "16627872"
    LIBKET_PROJ_ID: "16638729"
    KBW_PATH: "src/ket/clib/libs/kbw"
    LIBKET_PATH: "src/ket/clib/libs/libket"
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git curl ca-certificates
    - rm -rf /var/lib/apt/lists/*
    - uv pip install --system build
  script:
    - KBW_HASH=$(git rev-parse --short=8 HEAD:${KBW_PATH})
    - LIBKET_HASH=$(git rev-parse --short=8 HEAD:${LIBKET_PATH})
    - |
      curl --fail --location \
      "https://gitlab.com/api/v4/projects/${KBW_PROJ_ID}/packages/generic/kbw/${KBW_HASH}/kbw.dll" \
      --create-dirs --output src/ket/clib/libs/kbw.dll
    - |
      curl --fail --location \
      "https://gitlab.com/api/v4/projects/${LIBKET_PROJ_ID}/packages/generic/libket/${LIBKET_HASH}/ket.dll" \
      --create-dirs --output src/ket/clib/libs/ket.dll

    - python setup.py bdist_wheel -p win-amd64
  artifacts:
    paths:
      - dist/*.whl
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

Package Source Code:
  image: ghcr.io/astral-sh/uv:python3.10-trixie-slim
  stage: build
  before_script:
    - uv pip install --system build
  script:
    - python -m build -s
  artifacts:
    paths:
      - dist/ket_lang*.tar.gz

Lint:
  image: ghcr.io/astral-sh/uv:python3.10-trixie-slim
  stage: lint
  script:
    - uvx pylint src
    - uvx reuse lint

Test:
  image: ghcr.io/astral-sh/uv:python3.10-trixie-slim
  stage: test
  script:
    - uv pip install --system `ls wheelhouse/ket_lang*manylinux_2_28_x86_64.whl`[ibm,amazon] pytest pytest-cov
    - pytest
  artifacts:
    paths:
      - htmlcov

PyPI Upload:
  image: ghcr.io/astral-sh/uv:python3.10-trixie-slim
  stage: deploy
  before_script:
    - uv pip install --system twine
  script:
    - python -m twine upload dist/* wheelhouse/*
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PROJECT_PATH == "quantum-ket/ket"'

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
