# SPDX-FileCopyrightText: 2020 Evandro Chagas Ribeiro da Rosa <evandro@quantuloop.com>
# SPDX-FileCopyrightText: 2020 Rafael de Santiago <r.santiago@ufsc.br>
#
# SPDX-License-Identifier: Apache-2.0

stages:
  - lint
  - build
  - test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

Build Linux x86_64 Wheels:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - ./scripts/wheel-linux-x86_64.sh
  artifacts:
    paths:
      - wheelhouse/*.whl

Build Windows x86_64 Wheels:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - ./scripts/wheel-windows-x86_64.sh
  artifacts:
    paths:
      - wheelhouse/*.whl

Package Source Code:
  image: python:3.10-slim
  stage: build
  script:
    - pip install build
    - python -m build -s
  artifacts:
    paths:
      - dist/ket_lang*.tar.gz

Lint:
  image: python:3.10-slim
  stage: lint
  script:
    - pip install pipx
    - pipx run pylint src
    - pipx run reuse lint

Test:
  image: python:3.10-slim
  stage: test
  script:
    - pip install `ls wheelhouse/ket_lang*manylinux_2_28_x86_64.whl`[ibm] pytest pytest-cov
    - pytest
  artifacts:
    paths:
      - htmlcov

PyPI Upload:
  image: python:3.10-alpine
  stage: deploy
  script:
    - pip install twine
    - python -m twine upload dist/* wheelhouse/*
  only:
    - master

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
