# SPDX-FileCopyrightText: 2020 Evandro Chagas Ribeiro da Rosa <evandro@quantuloop.com>
# SPDX-FileCopyrightText: 2020 Rafael de Santiago <r.santiago@ufsc.br>
#
# SPDX-License-Identifier: Apache-2.0

stages:
  - build
  - test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

Build Wheels:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - ./scripts/make_wheel.sh
  artifacts:
    paths:
      - wheelhouse/*.whl

Package Source Code:
  image: python:3-slim
  stage: build
  script:
    - pip install build
    - python -m build -s
  artifacts:
    paths:
      - dist/ket-lang*.tar.gz

Lint:
  image: python:3-slim
  stage: test
  script:
    - pip install pipx
    - pipx run pylint src
    - pipx run reuse lint

Test:
  image: python:3-slim
  stage: test
  script:
    - pip install wheelhouse/ket_lang*manylinux_2_28_x86_64.whl pytest pytest-cov
    - pytest
  artifacts:
    paths:
      - htmlcov

PyPI Upload:
  image: python:alpine3.16
  stage: deploy
  script:
    - pip install twine
    - python -m twine upload dist/* wheelhouse/*
  only:
    - master

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
