stages:
  - build
  - test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

Build Wheels:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - ./scripts/make_wheel.sh
  artifacts:
    paths:
      - wheelhouse/*.whl

Package Source Code:
  image: python:3-slim
  stage: build
  script:
    - pip install build
    - python -m build -s
  artifacts:
    paths:
      - dist/ket-lang*.tar.gz

Test Wheel:
  image: python:3.8-slim
  stage: test
  script:
    - pip install wheelhouse/ket*x86_64.whl flake8 pylint pytest pytest-cov numpy
    - python -m flake8 src/ket
    - python -m pylint --disable=C0114 src/ket
    - python -m pytest

PyPI Upload:
  image: python:alpine3.16
  stage: deploy
  script:
    - pip install twine
    - python -m twine upload dist/* wheelhouse/*
  only:
    - master

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
