# SPDX-FileCopyrightText: 2024 Evandro Chagas Ribeiro da Rosa <evandro@quantuloop.com>
#
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "Ket"
SPDX-PackageSupplier = "Evandro Chagas Ribeiro da Rosa <evandro@quantuloop.com>"
SPDX-PackageDownloadLocation = "https://gitlab.com/quantum-ket/ket"
annotations = []
